Repository khulnasoft/pr-insight, pull requests merged in 2024-12, with the labels that each got.

#82 Create azure-pipelines.yml
  pr_insight/settings/azure-pipelines.yml
Labels: Review effort [1-5]: 2

#84 Tr/3 way prs
  pr_insight/algo/git_patch_processing.py
  pr_insight/git_providers/bitbucket_server_provider.py
  pr_insight/git_providers/github_provider.py
  pr_insight/tools/pr_code_suggestions.py
Labels: Review effort [1-5]: 3

#89 Refactor is_bot_user function to improve actor type handling
  pr_insight/servers/bitbucket_app.py
Labels: Review effort [1-5]: 2

#92 Update pr_config.py
  pr_insight/tools/pr_add_docs.py
  pr_insight/tools/pr_config.py
Labels: Review effort [1-5]: 1
