Repository khulnasoft/pr-insight, pull requests merged in 2024-10, with the labels that each got.

#62 Dev
  .github/workflows/docs-ci.yaml
  .pr_insight.toml
  docs/docs/index.md
  docs/docs/overview/index.md
  docs/docs/overview/pr_insight_pro.md
  docs/docs/tools/review.md
  pr_insight/algo/utils.py
  pr_insight/settings/configuration.toml
  pr_insight/settings/pr_description_prompts.toml
  pr_insight/settings/pr_reviewer_prompts.toml
  pr_insight/tools/pr_description.py
  pr_insight/tools/pr_reviewer.py
  pr_insight/tools/ticket_pr_compliance_check.py
  pyproject.toml
  tests/unittest/test_convert_to_markdown.py
Labels: enhancement, Tests, Review effort [1-5]: 3

#64 Update github.md
  docs/docs/installation/github.md
  docs/docs/installation/locally.md
  docs/docs/installation/pr_insight_pro.md
Labels: Review effort [1-5]: 2

#65 Fix code scanning alert no. 56: Jinja2 templating with autoescape=False
  pr_insight/tools/pr_code_suggestions.py
Labels: Review effort [1-5]: 2, Bug fix with tests

#67 Update requirements.txt
  pr_insight/tools/pr_code_suggestions.py
  requirements.txt
Labels: dependencies, Review effort [1-5]: 1, bug fix

#68 Fix code scanning alert no. 52: Jinja2 templating with autoescape=False
  pr_insight/tools/pr_add_docs.py
Labels: Review effort [1-5]: 2, bug fix

#69 Fix code scanning alert no. 53: Jinja2 templating with autoescape=False
  pr_insight/tools/pr_generate_labels.py
Labels: Review effort [1-5]: 2, bug fix
