Repository khulnasoft/pr-insight, pull requests merged in 2024-06, with the labels that each got.

#6 check
  tests/unittest/test_convert_to_markdown.py
Labels: Review effort [1-5]: 2, Tests

#7 Update Dockerfile
  docker/Dockerfile
  docs/docs/tools/describe.md
  docs/docs/tools/improve.md
  pr_assistant/git_providers/bitbucket_provider.py
  pr_assistant/git_providers/github_provider.py
  pr_assistant/servers/azuredevops_server_webhook.py
  pr_assistant/servers/gunicorn_config.py
  pr_assistant/settings/pr_evaluate_prompt_response.toml
  pr_assistant/settings/pr_reviewer_prompts.toml
Labels: enhancement, Review effort [1-5]: 2

#17 Master
  pr_assistant/algo/ai_handlers/litellm_ai_handler.py
  pr_assistant/algo/utils.py
  pr_assistant/git_providers/codecommit_client.py
  pr_assistant/git_providers/git_provider.py
  pr_assistant/git_providers/github_provider.py
  pr_assistant/servers/github_app.py
  pr_assistant/servers/gitlab_webhook.py
  pr_assistant/servers/help.py
  pr_assistant/tools/pr_add_docs.py
  pr_assistant/tools/pr_code_suggestions.py
  pr_assistant/tools/pr_description.py
  pr_assistant/tools/pr_help_message.py
  pr_assistant/tools/pr_questions.py
  pr_assistant/tools/pr_reviewer.py
  pr_assistant/tools/pr_update_changelog.py
Labels: enhancement, dependencies, Review effort [1-5]: 2
